columns:
  addr:
  - 登録住所
  - 住所
  addr_id:
  - 本人確認登録時住所
  - 本人住所
  email:
  - メールアドレス
  - メール アドレス
  - Email
  - E-mail
  name:
  - 氏名
  - 名前
  tel:
  - 電話番号
  - TEL
  - Phone
  url:
  - 閲覧用URL
  - URL
csv:
  encoding: utf-8-sig
excel:
  font_name: メイリオ
paths:
  bak_dir: bak
  csv_pattern: output/CustList_{yyyymmdd}.csv
  logs_dir: logs
  output_excel: output/CustList.xlsx
  tmp_dir: tmp
serial:
  digits: 4
  prefix: TR
  random_suffix:
    charset: ABCDEF
    length: 1
  start: 706
title_keywords:
- 【
- ■
- ◆
